version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb_currency:/data/mongodb_currency

  currency_app:
    build: ./
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: "${APP_PORT}"
    depends_on:
      - mongodb
